// <auto-generated />
namespace RedArbor_Jmendez_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddtableLogApiCalls : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddtableLogApiCalls));
        
        string IMigrationMetadata.Id
        {
            get { return "202209271819160_Add-table-LogApiCalls"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
