// <auto-generated />
namespace RedArbor_Jmendez_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddTableEmployees : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTableEmployees));
        
        string IMigrationMetadata.Id
        {
            get { return "202209261422125_Add-Table-Employees"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
